### ISSUE TITLE
ESLint check fails for `quotes` rule with allowTemplateLiterals

### ISSUE THREAD

**Issue by mesaugat** [codeclimate/codeclimate-eslint#171]
For this rule:

```js
"quotes": [2, "single", {"allowTemplateLiterals": true}]
```

CodeClimate is showing me this error:

```bash
Error: /code/.eslintrc:
	Configuration for rule "quotes" is invalid:
	Value "[object Object]" must be an enum value.

    at validateRuleOptions (/usr/src/app/node_modules/eslint/lib/config/config-validator.js:102:15)
    at /usr/src/app/node_modules/eslint/lib/config/config-validator.js:148:13
    at Array.forEach (native)
    at Object.validate (/usr/src/app/node_modules/eslint/lib/config/config-validator.js:147:35)
    at Object.load (/usr/src/app/node_modules/eslint/lib/config/config-file.js:394:19)
    at loadConfig (/usr/src/app/node_modules/eslint/lib/config.js:74:33)
    at getLocalConfig (/usr/src/app/node_modules/eslint/lib/config.js:177:23)
    at Config.getConfig (/usr/src/app/node_modules/eslint/lib/config.js:272:22)
    at CLIEngine.getConfigForFile (/usr/src/app/node_modules/eslint/lib/cli-engine.js:715:29)
    at module.exports (/usr/src/app/lib/validate_config.js:9:22)
```

I am using `"eslint": "^3.12.2"` in my local system and it doesn't show any problem.

**Comment by mesaugat** [comment]
CodeClimate uses ESLint version 1 by default. For anyone who encounters this problem should create a `.codeclimate.yml` file and specify the ESLint version in their repository. 

```yaml
engines:
  eslint:
    channel: eslint-3
    enabled: true
```

I did not have `.codeclimate.yml` in my repository. Thus, CodeClimate used ESLint version 1 by default.
