### ISSUE TITLE
eslint-4 "react/sort-prop-types" and "react/jsx-no-bind" are invalid

### ISSUE THREAD

**Issue by leonardofaria** [codeclimate/codeclimate-eslint#354]
## Actual Behavior

ESLint doesn't work
I have two properties on my .eslintrc that are breaking my setup

````json
"react/jsx-no-bind": [
  2,
  {
    "ignoreRefs": false,
    "allowArrowFunctions": true,
    "allowFunctions": false,
    "allowBind": false
  }
],
"react/sort-prop-types": [
  1,
  {
    "callbacksLast": true,
    "ignoreCase": true,
    "requiredFirst": false,
    "sortShapeProp": true
  }
]
````

The rules match the expected format (links at the bottom of this page) but I was unable to make this work.
Also, if I remove the rules it seems like the eslint is not using the `.eslintrc` from my project.

## Expected Behavior

ESLint works

## Steps to reproduce

My `.codeclimate.json`

````json
{
  "checks": {
    "argument-count": {
      "enabled": true
    },
    "complex-logic": {
      "enabled": true
    },
    "file-lines": {
      "enabled": false
    },
    "identical-code": {
      "enabled": true
    },
    "method-complexity": {
      "enabled": true
    },
    "method-count": {
      "enabled": true
    },
    "method-lines": {
      "enabled": true
    },
    "nested-control-flow": {
      "enabled": true
    },
    "return-statements": {
      "enabled": true
    },
    "similar-code": {
      "enabled": true
    }
  },
  "exclude_patterns": [
    "config/",
    "db/",
    "dist/",
    "features/",
    "**/node_modules/",
    "script/",
    "**/spec/",
    "**/test/",
    "**/tests/",
    "**/vendor/",
    "**/*_test.go",
    "**/*.d.ts",
    "**/*.stories.js",
    "**/*.spec.js"
  ],
  "plugins": {
    "apexmetrics": {
      "enabled": false
    },
    "brakeman": {
      "enabled": false
    },
    "brakeman-pro": {
      "enabled": false
    },
    "bundler-audit": {
      "enabled": false
    },
    "checkstyle": {
      "enabled": false
    },
    "coffeelint": {
      "enabled": false
    },
    "csslint": {
      "enabled": false
    },
    "eslint": {
      "enabled": true,
      "channel": "eslint-4"
    },
    "fixme": {
      "enabled": false
    },
    "flog": {
      "enabled": false
    },
    "foodcritic": {
      "enabled": false
    },
    "git-legal": {
      "enabled": false
    },
    "gnu-complexity": {
      "enabled": false
    },
    "gofmt": {
      "enabled": false
    },
    "golint": {
      "enabled": false
    },
    "govet": {
      "enabled": false
    },
    "grep": {
      "enabled": false
    },
    "haxe-checkstyle": {
      "enabled": false
    },
    "hlint": {
      "enabled": false
    },
    "kibit": {
      "enabled": false
    },
    "markdownlint": {
      "enabled": false
    },
    "nodesecurity": {
      "enabled": false
    },
    "pep8": {
      "enabled": false
    },
    "phan": {
      "enabled": false
    },
    "phpcodesniffer": {
      "enabled": false
    },
    "phpmd": {
      "enabled": false
    },
    "pmd": {
      "enabled": false
    },
    "radon": {
      "enabled": false
    },
    "reek": {
      "enabled": false
    },
    "rubocop": {
      "enabled": false
    },
    "rubymotion": {
      "enabled": false
    },
    "shellcheck": {
      "enabled": false
    },
    "scss-lint": {
      "enabled": true
    },
    "sonar-java": {
      "enabled": false
    },
    "sonar-php": {
      "enabled": false
    },
    "sonar-python": {
      "enabled": false
    },
    "stylelint": {
      "enabled": false
    },
    "tailor": {
      "enabled": false
    },
    "tslint": {
      "enabled": false
    },
    "vint": {
      "enabled": false
    },
    "watson": {
      "enabled": false
    }
  },
  "version": "2"
}
````

My `.eslintrc`: 

````json
{
  "root": true,
  "parser": "babel-eslint",
  "extends": [
    "airbnb",
    "eslint:recommended",
    "plugin:react/recommended",
    "plugin:jsx-a11y/recommended"
  ],
  "env": {
    "browser": true,
    "node": true,
    "jest": true,
    "es6": true,
    "jquery": true
  },
  "plugins": [
    "react",
    "jsx-a11y"
  ],
  "globals": {
    "__DEVELOPMENT__": true
  },
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "rules": {
    "arrow-parens": [
      "error",
      "always"
    ],
    "arrow-body-style": [
      2,
      "as-needed"
    ],
    "comma-dangle": [
      2,
      "always-multiline"
    ],
    "import/imports-first": 0,
    "import/newline-after-import": 2,
    "import/no-dynamic-require": 0,
    "import/no-extraneous-dependencies": 0,
    "import/no-named-as-default": 0,
    "import/no-unresolved": 0,
    "import/extensions": 0,
    "import/prefer-default-export": 2,
    "indent": [
      2,
      2,
      {
        "SwitchCase": 1
      }
    ],
    "jsx-a11y/aria-props": 2,
    "jsx-a11y/heading-has-content": 2,
    "jsx-a11y/label-has-for": [
      2,
      {
        "required": {
          "some": ["nesting", "id"]
        }
      }
    ],
    "jsx-a11y/mouse-events-have-key-events": 2,
    "jsx-a11y/role-has-required-aria-props": 2,
    "jsx-a11y/role-supports-aria-props": 2,
    "max-len": 2,
    "newline-per-chained-call": 0,
    "no-confusing-arrow": 0,
    "no-console": 1,
    "no-use-before-define": 0,
    "prefer-template": 2,
    "class-methods-use-this": 2,
    "require-yield": 0,
    "import/no-webpack-loader-syntax": 0,
    "semi": [
      2,
      "never"
    ],
    "react/boolean-prop-naming": 2,
    "react/destructuring-assignment": 2,
    "react/forbid-prop-types": 0,
    "react/jsx-filename-extension": 0,
    "react/jsx-first-prop-new-line": [
      2,
      "multiline"
    ],
    "react/jsx-no-target-blank": 0,
    "react/jsx-no-bind": [
      2,
      {
        "ignoreRefs": false,
        "allowArrowFunctions": true,
        "allowFunctions": false,
        "allowBind": false
      }
    ],
    "react/jsx-sort-props": [
      1, {
        "callbacksLast": true,
        "shorthandFirst": false,
        "shorthandLast": true,
        "ignoreCase": true,
        "noSortAlphabetically": false
      }
    ],
    "react/no-unused-prop-types": 2,
    "react/no-unused-state": 2,
    "react/prefer-stateless-function": 2,
    "react/prop-types": 2,
    "react/require-extension": 0,
    "react/self-closing-comp": 0,
    "react/sort-prop-types": [
      1,
      {
        "callbacksLast": true,
        "ignoreCase": true,
        "requiredFirst": false,
        "sortShapeProp": true
      }
    ]
  }
}
````
Output:

````
CODECLIMATE_DEBUG=1 codeclimate analyze -e eslint
Starting analysis
I, [2017-12-16T01:45:00.873121 #1]  INFO -- : starting engine eslint
D, [2017-12-16T01:48:11.280714 #1] DEBUG -- : /config.json content: {"enabled"=>true, "channel"=>"eslint-4", "include_paths"=>[".babelrc", ".codeclimate.json", ".DS_Store", ".eslintrc", ".env-example", "PULL_REQUEST_TEMPLATE.md", ".storybook/", ".editorconfig", "webpack.build.config.js", "README.md", "yarn.lock", ".gitignore", "package.json", "scripts/", ".sass-lint.yml", "lib/", ".flowconfig", "AUTHORS.txt", "postcss.config.js", ".circleci/", "coverage/", "src/jest.setup.js", "src/index.js", "src/utils/", "src/styles/", "src/components/Dropdown/index.js", "src/components/Dropdown/Dropdown.js", "src/components/Dropdown/Dropdown.scss", "src/components/Dropdown/Item/", "src/components/Dropdown/Menu/", "src/components/Dropdown/ItemHeader/", "src/components/Dropdown/Filter/", "src/components/Dropdown/Header/", "src/components/Calendar/Calendar.scss", "src/components/Calendar/index.js", "src/components/Calendar/Calendar.js", "src/components/Calendar/__snapshots__/", "src/components/Card/Card.scss", "src/components/Card/index.js", "src/components/Card/Card.js", "src/components/Card/__snapshots__/", "src/components/Loading/Loading.js", "src/components/Loading/index.js", "src/components/Loading/Loading.scss", "src/components/Input/index.js", "src/components/Input/Input.scss", "src/components/Input/ValidatedInput.js", "src/components/Input/Input.js", "src/components/TitleBar/TitleBar.scss", "src/components/TitleBar/TitleBar.js", "src/components/TitleBar/index.js", "src/components/TitleBar/__snapshots__/", "src/components/Checkbox/Checkbox.scss", "src/components/Checkbox/index.js", "src/components/Checkbox/Checkbox.js", "src/components/Checkbox/__snapshots__/", "src/components/index.js", "src/components/Toggle/", "src/components/EmptyState/index.js", "src/components/EmptyState/EmptyState.js", "src/components/EmptyState/EmptyState.scss", "src/components/Button/Button.scss", "src/components/Button/index.js", "src/components/Button/Button.js", "src/components/Button/__snapshots__/", "src/components/BetweenInput/index.js", "src/components/BetweenInput/BetweenInput.scss", "src/components/BetweenInput/BetweenInput.js", "src/components/ItemHeader/", "src/components/Select/Select.scss", "src/components/Select/index.js", "src/components/Select/Select.js", "src/components/Modal/ModalBody.js", "src/components/Modal/index.js", "src/components/Modal/ModalFooter.js", "src/components/Modal/Modal.js", "src/components/Modal/Modal.scss", "src/components/Modal/__snapshots__/", "src/components/MultiSelect/MultiSelect.js", "src/components/MultiSelect/CheckboxItem/", "src/components/MultiSelect/CheckboxList/", "src/components/MultiSelect/ItemList/", "src/components/MultiSelect/index.js", "src/components/MultiSelect/MultiSelect.scss", "src/components/MultiSelect/Item/", "src/components/MultiSelect/ActionItem/", "src/components/MultiSelect/Filter/", "src/components/MultiSelect/Header/", "src/shims.js"], "debug"=>"1"}
D, [2017-12-16T01:48:11.291831 #1] DEBUG -- : docker run: ["docker", "run", "--name", "cc-engines-eslint-eslint-4-a398ec91-59d3-4cc4-9ac7-a082b447d37f", "--cap-drop", "all", "--label", "com.codeclimate.label=a03979e8-f6b0-4b70-be50-a60c30678596", "--log-driver", "none", "--memory", "1024000000", "--memory-swap", "-1", "--net", "none", "--rm", "--volume", "/Users/leonardo/workspace/thinkific/elements-library:/code:ro", "--volume", "/tmp/cc/48ddc454-3ee3-4d55-a348-e2dc1a4c5fdb:/config.json:ro", "--user", "9000:9000", "codeclimate/codeclimate-eslint:eslint-4"]
D, [2017-12-16T01:48:12.276035 #1] DEBUG -- : engine stderr: /usr/src/app/lib/validate_config.js:18
D, [2017-12-16T01:48:12.276175 #1] DEBUG -- : engine stderr:         throw e;
D, [2017-12-16T01:48:12.276231 #1] DEBUG -- : engine stderr:         ^
D, [2017-12-16T01:48:12.276259 #1] DEBUG -- : engine stderr:
D, [2017-12-16T01:48:12.276295 #1] DEBUG -- : engine stderr: Error: /code/.eslintrc:
D, [2017-12-16T01:48:12.276319 #1] DEBUG -- : engine stderr: 	Configuration for rule "react/sort-prop-types" is invalid:
D, [2017-12-16T01:48:12.276353 #1] DEBUG -- : engine stderr: 	Value "[object Object]" should NOT have additional properties.
D, [2017-12-16T01:48:12.276380 #1] DEBUG -- : engine stderr:
D, [2017-12-16T01:48:12.276409 #1] DEBUG -- : engine stderr:     at validateRuleOptions (/usr/local/node_modules/eslint/lib/config/config-validator.js:113:15)
D, [2017-12-16T01:48:12.276432 #1] DEBUG -- : engine stderr:     at Object.keys.forEach.id (/usr/local/node_modules/eslint/lib/config/config-validator.js:153:9)
D, [2017-12-16T01:48:12.276454 #1] DEBUG -- : engine stderr:     at Array.forEach (native)
D, [2017-12-16T01:48:12.276471 #1] DEBUG -- : engine stderr:     at validateRules (/usr/local/node_modules/eslint/lib/config/config-validator.js:152:30)
D, [2017-12-16T01:48:12.276516 #1] DEBUG -- : engine stderr:     at Object.validate (/usr/local/node_modules/eslint/lib/config/config-validator.js:230:5)
D, [2017-12-16T01:48:12.276562 #1] DEBUG -- : engine stderr:     at loadFromDisk (/usr/local/node_modules/eslint/lib/config/config-file.js:549:19)
D, [2017-12-16T01:48:12.276617 #1] DEBUG -- : engine stderr:     at Object.load (/usr/local/node_modules/eslint/lib/config/config-file.js:592:20)
D, [2017-12-16T01:48:12.276641 #1] DEBUG -- : engine stderr:     at Config.getLocalConfigHierarchy (/usr/local/node_modules/eslint/lib/config.js:226:44)
D, [2017-12-16T01:48:12.276684 #1] DEBUG -- : engine stderr:     at Config.getConfigHierarchy (/usr/local/node_modules/eslint/lib/config.js:180:43)
D, [2017-12-16T01:48:12.276714 #1] DEBUG -- : engine stderr:     at Config.getConfigVector (/usr/local/node_modules/eslint/lib/config.js:285:21)
I, [2017-12-16T01:48:12.555645 #1]  INFO -- : finished engine eslint
error: (CC::CLI::Analyze::EngineFailure) engine eslint failed with status 1 and stderr
/usr/src/app/lib/validate_config.js:18
        throw e;
        ^

Error: /code/.eslintrc:
	Configuration for rule "react/sort-prop-types" is invalid:
	Value "[object Object]" should NOT have additional properties.

    at validateRuleOptions (/usr/local/node_modules/eslint/lib/config/config-validator.js:113:15)
    at Object.keys.forEach.id (/usr/local/node_modules/eslint/lib/config/config-validator.js:153:9)
    at Array.forEach (native)
    at validateRules (/usr/local/node_modules/eslint/lib/config/config-validator.js:152:30)
    at Object.validate (/usr/local/node_modules/eslint/lib/config/config-validator.js:230:5)
    at loadFromDisk (/usr/local/node_modules/eslint/lib/config/config-file.js:549:19)
    at Object.load (/usr/local/node_modules/eslint/lib/config/config-file.js:592:20)
    at Config.getLocalConfigHierarchy (/usr/local/node_modules/eslint/lib/config.js:226:44)
    at Config.getConfigHierarchy (/usr/local/node_modules/eslint/lib/config.js:180:43)
    at Config.getConfigVector (/usr/local/node_modules/eslint/lib/config.js:285:21)
D, [2017-12-16T01:48:12.555837 #1] DEBUG -- : backtrace: /usr/src/app/lib/cc/analyzer/raising_container_listener.rb:23:in `finished'
	/usr/src/app/lib/cc/analyzer/composite_container_listener.rb:13:in `block in finished'
	/usr/src/app/lib/cc/analyzer/composite_container_listener.rb:13:in `each'
	/usr/src/app/lib/cc/analyzer/composite_container_listener.rb:13:in `finished'
	/usr/src/app/lib/cc/analyzer/bridge.rb:52:in `block (2 levels) in run'
	/usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:63:in `with_spinner'
	/usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:41:in `block in engine_running'
	/usr/src/app/lib/cc/analyzer/formatters/formatter.rb:31:in `engine_running'
	/usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:40:in `engine_running'
	/usr/src/app/lib/cc/analyzer/bridge.rb:37:in `block in run'
	/usr/src/app/lib/cc/analyzer/bridge.rb:34:in `each'
	/usr/src/app/lib/cc/analyzer/bridge.rb:34:in `run'
	/usr/src/app/lib/cc/cli/analyze.rb:36:in `run'
	/usr/src/app/lib/cc/cli/command.rb:73:in `execute'
	/usr/src/app/lib/cc/cli/runner.rb:25:in `run'
	/usr/src/app/lib/cc/cli/runner.rb:9:in `run'
	/usr/src/app/bin/codeclimate:12:in `<main>'
````

## Relevant links

https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-prop-types.md
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md

**Comment by efueger** [comment]
Looks like these rules were changed in later versions of the plugin and might be fixed by upgrading. 
- This channel is [currently using v7.4.0](https://github.com/codeclimate/codeclimate-eslint/blob/channel/eslint-4/package.json#L58), 
- and these 2 rules were [touched in 7.5.0 and 7.5.1](https://github.com/yannickcr/eslint-plugin-react/releases).

**Comment by efueger** [comment]
Updated here: https://github.com/codeclimate/codeclimate-eslint/issues/355
