### ISSUE TITLE
eslint-plugin-security: TypeError: Cannot read property 'recommended' of undefined

### ISSUE THREAD

**Issue by davehenton** [codeclimate/codeclimate-eslint#359]
I'm working with a customer who is running into an error surrounding [eslint-plugin-security](https://www.npmjs.com/package/eslint-plugin-security)

When the user has the following configuration in their `.eslintrc.json`:

```
"plugins": [
  "security"
],
"extends": [
  "plugin:security/recommended"
]
```
They run into the following error:

```
engine eslint failed with status 1 and stderr 
/usr/local/node_modules/eslint/lib/config/config-file.js:434
            throw e;
            ^

TypeError: Cannot read property 'recommended' of undefined
Referenced from: /code/./.eslintrc.json
    at loadConfigFile (/usr/local/node_modules/eslint/lib/config/config-file.js:217:40)
    at load (/usr/local/node_modules/eslint/lib/config/config-file.js:535:18)
    at configExtends.reduceRight.e (/usr/local/node_modules/eslint/lib/config/config-file.js:424:36)
    at Array.reduceRight (native)
    at applyExtends (/usr/local/node_modules/eslint/lib/config/config-file.js:408:28)
    at Object.load (/usr/local/node_modules/eslint/lib/config/config-file.js:566:22)
    at loadConfig (/usr/local/node_modules/eslint/lib/config.js:63:33)
    at new Config (/usr/local/node_modules/eslint/lib/config.js:229:42)
    at CLIEngine.getConfigForFile (/usr/local/node_modules/eslint/lib/cli-engine.js:774:30)
    at Object.run (/usr/src/app/lib/eslint.js:236:56)
```

When the 'plugin:' flag is removed, they receive a different error:

```
Module not supported: eslint-config-security/recommended
ESLint is running with the /usr/local/node_modules/babel-eslint/index.js parser.

Ignoring the following rules that rely on module resolution:

* import/extensions
* import/no-unresolved
* import/no-extraneous-dependencies
* import/no-named-as-default
* import/no-absolute-path
* import/no-duplicates
* import/no-named-as-default-member

```

This is an OSS repository, which you can check out [here](https://github.com/CarbonCollins/tfl-unified-api-nodejs/blob/f6df35015d1252b9f7d1df2c2c77f86ec0700063/.eslintrc.json).

I'm not sure exactly what's going on here. Is it possible that it's related to [9771](https://github.com/eslint/eslint/issues/9771) or [9767](https://github.com/eslint/eslint/issues/9767)?

**Comment by guillaumearm** [comment]
I have the same issue with [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) 

my `.eslintrc` file contains :
```json
"plugins": [
  "prettier"
],
"extends": [
  "plugin:prettier/recommended"
]
```

error report from https://codeclimate.com : 

```
/usr/src/app/lib/validate_config.js:18
        throw e;
        ^

TypeError: Cannot read property 'recommended' of undefined
Referenced from: /code/.eslintrc
    at loadConfigFile (/usr/local/node_modules/eslint/lib/config/config-file.js:211:40)
    at loadFromDisk (/usr/local/node_modules/eslint/lib/config/config-file.js:486:18)
    at load (/usr/local/node_modules/eslint/lib/config/config-file.js:550:20)
    at configExtends.reduceRight.e (/usr/local/node_modules/eslint/lib/config/config-file.js:421:36)
    at Array.reduceRight (native)
    at applyExtends (/usr/local/node_modules/eslint/lib/config/config-file.js:403:28)
    at loadFromDisk (/usr/local/node_modules/eslint/lib/config/config-file.js:514:22)
    at Object.load (/usr/local/node_modules/eslint/lib/config/config-file.js:550:20)
    at Config.getLocalConfigHierarchy (/usr/local/node_modules/eslint/lib/config.js:228:44)
    at Config.getConfigHierarchy (/usr/local/node_modules/eslint/lib/config.js:180:43)
```

**Comment by efueger** [comment]
@davehenton - I had a conversation with another customer and found that using `channel: "eslint-4` resolves that type error 👍 

- I opened up a PR for your oss customer.

@guillaumearm 
- Can you test that out with your repo and let us know what you get? To do that, you'll add the [channel specification](https://docs.codeclimate.com/v1.0/docs/eslint#section-eslint-versions) in your [.codeclimate.yml](https://docs.codeclimate.com/v1.0/docs/advanced-configuration#section-plugins): 

- Let me know if you need any help!

**Comment by guillaumearm** [comment]
@efueger : 
- My actual `.codeclimate.yml` file is : https://github.com/char0n/ramda-adjunct/blob/master/.codeclimate.yml

- I succeed to get codeclimate working with `eslint-plugin-prettier` in this PR :  https://github.com/char0n/ramda-adjunct/pull/388

**Comment by efueger** [comment]
Thanks for the update @guillaumearm - glad you got that to work!
