### ISSUE TITLE
Unsupported Cypress plugin throws error

### ISSUE THREAD

**Issue by achton** [codeclimate/codeclimate-eslint#366]
# Bug Template

## Actual Behavior
The CC build fails entirely, instead of ignoring the unsupported plugin.

```
Module not supported: eslint-plugin-cypress
/usr/local/node_modules/eslint/lib/config/config-validator.js:137
            throw new Error(message);
            ^

Error: /code/frontend/.eslintrc:
	Environment key "cypress/globals" is unknown

    at Object.keys.forEach.env (/usr/local/node_modules/eslint/lib/config/config-validator.js:137:19)
    at Array.forEach (native)
    at validateEnvironment (/usr/local/node_modules/eslint/lib/config/config-validator.js:133:30)
    at Object.validate (/usr/local/node_modules/eslint/lib/config/config-validator.js:233:5)
    at loadFromDisk (/usr/local/node_modules/eslint/lib/config/config-file.js:507:19)
    at Object.load (/usr/local/node_modules/eslint/lib/config/config-file.js:550:20)
    at Config.loadSpecificConfig (/usr/local/node_modules/eslint/lib/config.js:139:46)
    at new Config (/usr/local/node_modules/eslint/lib/config.js:101:14)
    at new CLIEngine (/usr/local/node_modules/eslint/lib/cli-engine.js:420:23)
    at Object.run (/usr/src/app/lib/eslint.js:234:9)
```

## Expected Behavior

The unsupported plugin should simply be ignored, as per the docs.

## Steps to reproduce

> 1. _Include configurations used in your: <br>
> (1) .codeclimate.yml <br>
```
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      config: frontend/.eslintrc
      ignore_warnings: true
      extensions:
      - .js
```
> (2) config files for the oss analysis tool._<br>
**frontend/.eslintrc:**
```
{
  "parser": "babel-eslint",
  "extends": ["standard", "standard-react"],
  "plugins": [
    "cypress"
  ],
  "env": {
    "cypress/globals": true
  },
  "rules": {
    "object-curly-spacing": ["error", "always"],
    "react/jsx-curly-spacing": [2, { "when": "always", "children": true }]
  }
}
```

**Comment by schlenks** [comment]
Hitting this same ES10 issue right now as well. I have 2 `.eslintrc` files and codeclimate is not consuming the correct one (it's trying to consume the cypress file).

**Comment by rluncasu** [comment]
I've had the same issue on a project of mine (unrelated to codeclimate):
Environment key "cypress/globals" is unknown

upgrading cypress & eslint-plugin-cypress to these versions (latest as I'm writing this) solved the problem without any other changes to eslintrc:
```json
  "devDependencies": {
    "cypress": "^2.1.0",
    "eslint-plugin-cypress": "^2.0.1"
  }
```

**Comment by nickytonline** [comment]
I'm coming across this issue as well.

./.eslintrc:

```
module.exports = {
  extends: ['airbnb-base/legacy', 'prettier'],
  parserOptions: {
    ecmaVersion: 6,
  },
  env: {
    browser: true,
  },
  plugins: ['ignore-erb'],
};

```

./app/javascript/.eslintrc

```
module.exports = {
  parser: 'babel-eslint',
  extends: ['airbnb', 'prettier'],
  parserOptions: {
    ecmaVersion: 2017,
  },
  settings: {
    react: {
      pragma: 'h',
    },
  },
  env: {
    jest: true,
    browser: true,
  },
  plugins: ['import', 'babel'],
  rules: {
    'import/no-extraneous-dependencies': [
      'error',
      {
        devDependencies: ['**/*.test.js', '**/*.test.jsx', '**/*.stories.jsx'],
      },
    ],
  },
  plugins: ['import'],
  rules: {
    'import/no-extraneous-dependencies': [
      'error',
      {
        devDependencies: ['**/*.test.js', '**/*.test.jsx', '**/*.stories.jsx'],
      },
    ],
    'import/prefer-default-export': 'off',
  },
  globals: {
    InstantClick: false,
    filterXSS: false,
  },
};

```

./cypress/.eslintrc:

```
{
  "parser": "babel-eslint",
  "extends": ["airbnb", "prettier"],
  "parserOptions": {
    "ecmaVersion": 2017
  },
  "plugins": ["chai-friendly", "cypress"],
  "env": {
    "cypress/globals": true
  },
  "rules": {
    "spaced-comment": "off",
    "no-unused-expressions": 0,
    "chai-friendly/no-unused-expressions": 2
  }
}
```

and the error I get is

```
Module not supported: eslint-plugin-ignore-erb
ESLint is running with the default parser.
Module not supported: eslint-plugin-chai-friendly
Module not supported: eslint-plugin-cypress
/usr/local/node_modules/eslint/lib/config/config-validator.js:138
                throw new Error(message.join(""));
                ^

Error: /code/cypress/.eslintrc:
	Environment key "cypress/globals" is unknown

    at Object.keys.forEach.env (/usr/local/node_modules/eslint/lib/config/config-validator.js:138:23)
    at Array.forEach (native)
    at validateEnvironment (/usr/local/node_modules/eslint/lib/config/config-validator.js:131:34)
    at Object.validate (/usr/local/node_modules/eslint/lib/config/config-validator.js:160:5)
    at Object.load (/usr/local/node_modules/eslint/lib/config/config-file.js:559:19)
    at loadConfig (/usr/local/node_modules/eslint/lib/config.js:63:33)
    at new Config (/usr/local/node_modules/eslint/lib/config.js:229:42)
    at /usr/src/app/lib/config_upgrader.js:235:22
    at Array.map (native)
    at Function.upgradeInstructions (/usr/src/app/lib/config_upgrader.js:231:29)
```

There is no code climate config in the repo. I'm assuming that means it's using a default configuration?

**Comment by llatinov** [comment]
I'm also hitting the same issue. I suppose CodeClimate should add **eslint-plugin-cypress** to its supported plugins: https://docs.codeclimate.com/docs/eslint#section-supported-plugins
Note that Cypress is getting more popular with almost 100K weekly downloads and CodeClimate should be up to date supporting popular plugins.

**Comment by nickytonline** [comment]
In the interim, I've uninstalled [eslint-plugin-cypress](https://github.com/cypress-io/eslint-plugin-cypress) and added the following keys into my .eslintrc

```
...
  "env": {
    "browser": true
  },
  "globals": {
    "cy": false,
    "Cypress": false,
    "describe": false,
    "context": false,
    "beforeEach": false,
    "afterEach": false,
    "it": false,
    "assert": false,
    "expect": false
  },
...
```

**Comment by efueger** [comment]
Hi all - this slipped through the cracks: thanks for the bump! 
- I'll check on getting eslint-plugin-cypress added to the supported plugins and will post an update soon.

**Comment by efueger** [comment]
Good news:
- **eslint-plugin-cypress** is now available 🎉
- we'll add that to `eslint-4` channel shortly   

Thanks again for the bump. 👌 

-----

PS: when not specified, the plugin's default [channel](https://docs.codeclimate.com/docs/eslint#section-eslint-versions) = `eslint-3`, tracked on the master branch of this project.
