### ISSUE TITLE
Need to update to babel-eslint 8.1.1

### ISSUE THREAD

**Issue by tobycox** [codeclimate/codeclimate-eslint#367]
# Bug Template

## Actual Behavior

Currently on channel/eslint-4 we get:
```
/usr/local/node_modules/eslint/lib/rules/no-unused-vars.js:406
            if (target.type === "VariableDeclarator") {
                      ^

TypeError: Cannot read property 'type' of undefined
    at isForInRef (/usr/local/node_modules/eslint/lib/rules/no-unused-vars.js:406:23)
    at variable.references.some.ref (/usr/local/node_modules/eslint/lib/rules/no-unused-vars.js:443:21)
    at Array.some (native)
    at isUsedVariable (/usr/local/node_modules/eslint/lib/rules/no-unused-vars.js:442:40)
    at collectUnusedVariables (/usr/local/node_modules/eslint/lib/rules/no-unused-vars.js:565:26)
    at Program:exit (/usr/local/node_modules/eslint/lib/rules/no-unused-vars.js:617:36)
    at listeners.(anonymous function).forEach.listener (/usr/local/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (native)
    at Object.emit (/usr/local/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/usr/local/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/usr/local/node_modules/eslint/lib/util/node-event-generator.js:280:22)
```

## Expected Behavior
Shouldn't have exception.

## Steps to reproduce
Use channel/eslint-4
With babel and babel-eslint

## Relevant links

This commit bumped eslint to 4.15.0: https://github.com/codeclimate/codeclimate-eslint/commit/05944399498b97cf922c4233cbebd382a88799b8

However without updating babel-eslint to 8.1.1 we'll hit this issue: https://github.com/eslint/eslint/issues/9767
Currently babel-eslint has just been left on ^8.0.0

**Comment by chrishulton** [comment]
Thanks for the investigation, `babel-eslint` has been updated to the latest version (8.2.1).
