### ISSUE TITLE
Add eslint-plugin-es5 to supported plugins

### ISSUE THREAD

**Issue by smmccrohan** [codeclimate/codeclimate-eslint#370]
Attempting to use the `eslint-plugin-es5` plugin (https://www.npmjs.com/package/eslint-plugin-es5), we're getting:

```
Module not supported: eslint-plugin-es5
/usr/local/node_modules/eslint/lib/config/config-file.js:434
            throw e;
            ^

Error: Failed to load config "plugin:es5/no-es2015" to extend from.
Referenced from: /code/.eslintrc.yml
    at configMissingError (/usr/local/node_modules/eslint/lib/config/config-file.js:193:19)
    at loadConfigFile (/usr/local/node_modules/eslint/lib/config/config-file.js:219:27)
    at load (/usr/local/node_modules/eslint/lib/config/config-file.js:535:18)
    at configExtends.reduceRight.e (/usr/local/node_modules/eslint/lib/config/config-file.js:424:36)
    at Array.reduceRight (native)
    at applyExtends (/usr/local/node_modules/eslint/lib/config/config-file.js:408:28)
    at Object.load (/usr/local/node_modules/eslint/lib/config/config-file.js:566:22)
    at loadConfig (/usr/local/node_modules/eslint/lib/config.js:63:33)
    at new Config (/usr/local/node_modules/eslint/lib/config.js:229:42)
    at CLIEngine.getConfigForFile (/usr/local/node_modules/eslint/lib/cli-engine.js:774:30)
```

Could we have the module added to the whitelist? And relatedly, is there a way to have CC recognize `extend` entries from modules that it has rejected and skip them, rather than failing?

**Comment by lasseborly** [comment]
Thanks for a great product @ale7714.

This would be a really nice addition to the whitelist and would greatly benefit our multiple ES5 code bases we need to have checked across our org. Thanks again.
