### ISSUE TITLE
TypeError: Cannot read property 'recommended' of undefined

### ISSUE THREAD

**Issue by efueger** [codeclimate/codeclimate-eslint#378]
# Bug

Sample OSS repo here: https://github.com/ai-wordsmith/codeclimatetest/tree/test
- (found this happening on a private repo, customer provided ^^)
- repo using **eslint version 3.17.1**. 
- **2 .eslintrc files** in the repo
- tried with all eslint-x channels in .codeclimate.com
- channel-3 supports this [eslint-plugin-security](https://github.com/codeclimate/codeclimate-eslint/blob/master/package.json#L85) plugin
- **Note:** I thought it might be related to [another reported issue](https://github.com/codeclimate/codeclimate-eslint/issues/359), but that workaround doesn't fix it.

## Actual Behavior
- Repo with .eslintrc using:
```
{
  "extends": "plugin:security/recommended",
  "plugins": [
      "security"
  ],
  "parserOptions": {
      "ecmaVersion": 6
  },
  "rules": {
      "semi": 2,
      "security/detect-object-injection": 0
  }
}
```

- CLI returns:
```
error: (CC::CLI::Analyze::EngineFailure) engine eslint failed with status 1 and stderr 
/usr/src/app/lib/validate_config.js:17
        throw e;
        ^

TypeError: Cannot read property 'recommended' of undefined
Referenced from: /code/.eslintrc

```

- .com analysis shows this message in the ESLint step:
```
No rules are configured. Make sure you have added a config file with rules enabled.
See our documentation at https://docs.codeclimate.com/docs/eslint for more information.
```

## CODECLIMATE_DEBUG

```
CODECLIMATE_DEBUG=1 codeclimate analyze -e eslint
Starting analysis
I, [2018-02-23T21:54:07.237071 #1]  INFO -- : starting engine eslint
D, [2018-02-23T21:54:07.252741 #1] DEBUG -- : /config.json content: {"channel"=>"stable", "include_paths"=>[".eslintrc", "broke.js"], "debug"=>"1"}
D, [2018-02-23T21:54:07.267531 #1] DEBUG -- : docker run: ["docker", "run", "--name", "cc-engines-eslint-stable-5ee83a8c-e18b-40f5-bd7b-3fc0eeedd967", "--cap-drop", "all", "--label", "com.codeclimate.label=a5f834ad-436d-4a3d-a746-0257bdf06b7d", "--log-driver", "none", "--memory", "1024000000", "--memory-swap", "-1", "--net", "none", "--rm", "--volume", "/Users/emily/workspace/codeclimatetest/lib:/code:ro", "--volume", "/tmp/cc/1222e557-f3d7-4c1d-b491-5edeb224c559:/config.json:ro", "--user", "9000:9000", "codeclimate/codeclimate-eslint"]
D, [2018-02-23T21:54:08.175691 #1] DEBUG -- : engine stderr: /usr/src/app/lib/validate_config.js:17
D, [2018-02-23T21:54:08.175803 #1] DEBUG -- : engine stderr:         throw e;
D, [2018-02-23T21:54:08.175884 #1] DEBUG -- : engine stderr:         ^
D, [2018-02-23T21:54:08.175970 #1] DEBUG -- : engine stderr: 
D, [2018-02-23T21:54:08.175991 #1] DEBUG -- : engine stderr: TypeError: Cannot read property 'recommended' of undefined
D, [2018-02-23T21:54:08.176011 #1] DEBUG -- : engine stderr: Referenced from: /code/.eslintrc
D, [2018-02-23T21:54:08.176031 #1] DEBUG -- : engine stderr:     at loadConfigFile (/usr/local/node_modules/eslint/lib/config/config-file.js:217:40)
D, [2018-02-23T21:54:08.176054 #1] DEBUG -- : engine stderr:     at load (/usr/local/node_modules/eslint/lib/config/config-file.js:535:18)
D, [2018-02-23T21:54:08.176074 #1] DEBUG -- : engine stderr:     at configExtends.reduceRight.e (/usr/local/node_modules/eslint/lib/config/config-file.js:424:36)
D, [2018-02-23T21:54:08.176091 #1] DEBUG -- : engine stderr:     at Array.reduceRight (native)
D, [2018-02-23T21:54:08.176109 #1] DEBUG -- : engine stderr:     at applyExtends (/usr/local/node_modules/eslint/lib/config/config-file.js:408:28)
D, [2018-02-23T21:54:08.176129 #1] DEBUG -- : engine stderr:     at Object.load (/usr/local/node_modules/eslint/lib/config/config-file.js:566:22)
D, [2018-02-23T21:54:08.176296 #1] DEBUG -- : engine stderr:     at loadConfig (/usr/local/node_modules/eslint/lib/config.js:63:33)
D, [2018-02-23T21:54:08.176355 #1] DEBUG -- : engine stderr:     at getLocalConfig (/usr/local/node_modules/eslint/lib/config.js:130:29)
D, [2018-02-23T21:54:08.176389 #1] DEBUG -- : engine stderr:     at Config.getConfig (/usr/local/node_modules/eslint/lib/config.js:260:26)
D, [2018-02-23T21:54:08.176421 #1] DEBUG -- : engine stderr:     at Config.getConfig (/usr/src/app/lib/eslint-patch.js:45:46)
I, [2018-02-23T21:54:08.514814 #1]  INFO -- : finished engine eslint
error: (CC::CLI::Analyze::EngineFailure) engine eslint failed with status 1 and stderr 
/usr/src/app/lib/validate_config.js:17
        throw e;
        ^

TypeError: Cannot read property 'recommended' of undefined
Referenced from: /code/.eslintrc
    at loadConfigFile (/usr/local/node_modules/eslint/lib/config/config-file.js:217:40)
    at load (/usr/local/node_modules/eslint/lib/config/config-file.js:535:18)
    at configExtends.reduceRight.e (/usr/local/node_modules/eslint/lib/config/config-file.js:424:36)
    at Array.reduceRight (native)
    at applyExtends (/usr/local/node_modules/eslint/lib/config/config-file.js:408:28)
    at Object.load (/usr/local/node_modules/eslint/lib/config/config-file.js:566:22)
    at loadConfig (/usr/local/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/usr/local/node_modules/eslint/lib/config.js:130:29)
    at Config.getConfig (/usr/local/node_modules/eslint/lib/config.js:260:26)
    at Config.getConfig (/usr/src/app/lib/eslint-patch.js:45:46)
D, [2018-02-23T21:54:08.515882 #1] DEBUG -- : backtrace: /usr/src/app/lib/cc/analyzer/raising_container_listener.rb:23:in `finished'
	/usr/src/app/lib/cc/analyzer/composite_container_listener.rb:13:in `block in finished'
	/usr/src/app/lib/cc/analyzer/composite_container_listener.rb:13:in `each'
	/usr/src/app/lib/cc/analyzer/composite_container_listener.rb:13:in `finished'
	/usr/src/app/lib/cc/analyzer/bridge.rb:52:in `block (2 levels) in run'
	/usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:63:in `with_spinner'
	/usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:41:in `block in engine_running'
	/usr/src/app/lib/cc/analyzer/formatters/formatter.rb:31:in `engine_running'
	/usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:40:in `engine_running'
	/usr/src/app/lib/cc/analyzer/bridge.rb:37:in `block in run'
	/usr/src/app/lib/cc/analyzer/bridge.rb:34:in `each'
	/usr/src/app/lib/cc/analyzer/bridge.rb:34:in `run'
	/usr/src/app/lib/cc/cli/analyze.rb:36:in `run'
	/usr/src/app/lib/cc/cli/command.rb:73:in `execute'
	/usr/src/app/lib/cc/cli/runner.rb:25:in `run'
	/usr/src/app/lib/cc/cli/runner.rb:9:in `run'
	/usr/src/app/bin/codeclimate:12:in `<main>'
```

**Comment by larkinscott** [comment]
We're currently using version ```1.3.0``` of ```eslint-plugin-security```. When I bump to the latest version ```1.4.0``` and test the image locally, the error disappears. I think that's because they added the ```recommended``` feature in April 2017 (https://github.com/nodesecurity/eslint-plugin-security/blob/master/CHANGELOG.md) and our current version pre-dates that. 

Going to bump this now and we should be all set.

**Comment by larkinscott** [comment]
This is in production now. Moving to acceptance.
