### ISSUE TITLE
Can't directly extend files in my dependencies (by relative path)

### ISSUE THREAD

**Issue by hon2a** [codeclimate/codeclimate-eslint#396]
## Actual Behavior

I have a package `parent` (alias, these are private packages) used as baseline for other packages. It contains default configurations for various tools we use, such as `babel`, `jest`, `eslint`. These are at their usual locations in the package, e.g. config for eslint is in the `.eslintrc` file.

Then I have a `child` package which depends on `parent`. Its tooling configurations extend the configurations from parent using relative paths, so that I don't have to have a separate package for each config.

```json
{
  "extends": "./node_modules/parent/.eslintrc"
}
```

When I run `codeclimate-eslint` on this setup, it fails with the following error:

```
/usr/src/app/lib/validate_config.js:17
        throw e;
        ^

Error: Cannot read config file: /code/node_modules/parent/.eslintrc
Error: ENOENT: no such file or directory, open '/code/node_modules/parent/.eslintrc'
Referenced from: /code/.eslintrc
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at readFile (/usr/local/node_modules/eslint/lib/config/config-file.js:70:24)
    at loadLegacyConfigFile (/usr/local/node_modules/eslint/lib/config/config-file.js:142:44)
    at loadConfigFile (/usr/local/node_modules/eslint/lib/config/config-file.js:241:22)
    at load (/usr/local/node_modules/eslint/lib/config/config-file.js:535:18)
    at configExtends.reduceRight.e (/usr/local/node_modules/eslint/lib/config/config-file.js:424:36)
    at Array.reduceRight (native)
    at applyExtends (/usr/local/node_modules/eslint/lib/config/config-file.js:408:28)
```

## Expected Behavior

Package `dependencies` should be properly installed before running the check and the files in them available to be directly extended.

**Comment by patrickbussmann** [comment]
I have the same issue here.

```
Running eslint: Done!
error: (CC::CLI::Analyze::EngineFailure) engine eslint failed with status 1 and stderr
fs.js:1003
  binding.lstat(pathModule._makeLong(path), statValues);
          ^

Error: ENOENT: no such file or directory, lstat 'app.bootstrap.js'
    at Error (native)
    at Object.fs.lstatSync (fs.js:1003:11)
    at isFileWithMatchingExtension (/usr/src/app/lib/eslint.js:96:20)
    at /usr/src/app/lib/eslint.js:144:59
    at Array.forEach (native)
    at /usr/src/app/lib/eslint.js:132:20
    at /usr/src/app/lib/eslint.js:191:12
    at runWithTiming (/usr/src/app/lib/eslint.js:36:20)
    at Object.run (/usr/src/app/lib/eslint.js:190:23)
    at Object.<anonymous> (/usr/src/app/bin/eslint.js:7:8)
```

**Comment by wfleming** [comment]
Re the original report here (which I'm sorry has gone so long without a reply): I think this is down to https://github.com/codeclimate/codeclimate/issues/480, which is a considered limitation on our part. We do not support installing `package.json` dependencies right now, sorry.

Patrick's issue looks a bit different, and I suspect is more about the docker volume mounting issues you discussed on an another issue? If I recall correctly, you're on Windows, and getting mounted container paths to work as desired on that OS is a bit weird.
