### ISSUE TITLE
"env" variable from react-native should work.

### ISSUE THREAD

**Issue by quinnbaetz** [codeclimate/codeclimate-eslint#413]
# Bug Template

## Actual Behavior

/usr/src/app/lib/validate_config.js:17
        throw e;
        ^

Error: /code/.eslintrc.js:
	Environment key "react-native/react-native" is unknown

    at Object.keys.forEach.env (/usr/local/node_modules/eslint/lib/config/config-validator.js:138:23)
    at Array.forEach (native)
    at validateEnvironment (/usr/local/node_modules/eslint/lib/config/config-validator.js:131:34)
    at Object.validate (/usr/local/node_modules/eslint/lib/config/config-validator.js:160:5)
    at Object.load (/usr/local/node_modules/eslint/lib/config/config-file.js:559:19)
    at loadConfig (/usr/local/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/usr/local/node_modules/eslint/lib/config.js:130:29)
    at Config.getConfig (/usr/local/node_modules/eslint/lib/config.js:260:26)
    at Config.getConfig (/usr/src/app/lib/eslint-patch.js:45:46)
    at CLIEngine.getConfigForFile (/usr/local/node_modules/eslint/lib/cli-engine.js:776:29)

## Expected Behavior

The engine should support plugins allowing global variables through the env.

## Steps to reproduce

Add the following to .eslintrc.js

```
module.exports = {
  "parser": "babel-eslint",
  "extends": "airbnb",
  "plugins": ["react", "react-native" ],
  "env": {
    "react-native/react-native": true,
  }
}
```

## Relevant links

https://www.npmjs.com/package/eslint-plugin-react-native

----
- ["env" variables from plugins should work ] 4-6 word issue title

**Comment by wfleming** [comment]
Hi @quinnbaetz, can you provide a bit more detail on what ENV vars in your environment need to be available to the plugin and why? I'm not very familiar with the `eslint-plugin-react-native` plugin, so I'm not clear on what env it's using for this.

**Comment by quinnbaetz** [comment]
It "whitelists all browser-like globals".  Currently I would use it for `fetch` and `require`.   I have added those to globals directly, but the above should still work.

**Comment by louy** [comment]
Any luck with this one?

**Comment by efueger** [comment]
HI @quinnbaetz - apologies for dropping this!
- I'll close it for now, but let me know if this is still relevant for us to investigate.

**Comment by sguha00** [comment]
I'm still getting this issue:

```
/usr/src/app/lib/validate_config.js:17
        throw e;
        ^

Error: /code/.eslintrc:
	Environment key "react-native/react-native" is unknown

    at Object.keys.forEach.env (/usr/local/node_modules/eslint/lib/config/config-validator.js:138:23)
    at Array.forEach (native)
    at validateEnvironment (/usr/local/node_modules/eslint/lib/config/config-validator.js:131:34)
    at Object.validate (/usr/local/node_modules/eslint/lib/config/config-validator.js:160:5)
    at Object.load (/usr/local/node_modules/eslint/lib/config/config-file.js:559:19)
    at loadConfig (/usr/local/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/usr/local/node_modules/eslint/lib/config.js:130:29)
    at Config.getConfig (/usr/local/node_modules/eslint/lib/config.js:260:26)
    at Config.getConfig (/usr/src/app/lib/eslint-patch.js:45:46)
    at CLIEngine.getConfigForFile (/usr/local/node_modules/eslint/lib/cli-engine.js:776:29)
```
