### ISSUE TITLE
Upgrade to Node 10+ for Prettier 2

### ISSUE THREAD

**Issue by SkipKayhil** [codeclimate/codeclimate-eslint#488]
# Bug Template

## Actual Behavior
```
error: (CC::CLI::Analyze::EngineFailure) engine eslint failed with status 1 and stderr 
/usr/local/node_modules/eslint/lib/linter/linter.js:1103
            throw err;
            ^
TypeError: text.trimEnd is not a function
Occurred while linting /code/babel.config.js:1
    at attachComments (/code/node_modules/prettier/index.js:14771:60)
    at coreFormat (/code/node_modules/prettier/index.js:14798:23)
    at format (/code/node_modules/prettier/index.js:15019:75)
    at formatWithCursor (/code/node_modules/prettier/index.js:15035:12)
    at args (/code/node_modules/prettier/index.js:51620:12)
    at Object.format (/code/node_modules/prettier/index.js:51640:12)
    at Program (/code/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js:241:41)
    at listeners.(anonymous function).forEach.listener (/usr/local/node_modules/eslint/lib/linter/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/usr/local/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
Could not analyze code quality for the repository at /code
```
## Expected Behavior
No errors
## Steps to reproduce

```
# .codeclimate.yml
version: "2"
plugins:
  eslint:
    enabled: true
    channel: "eslint-6"
```

```
# .eslintrc.js
module.exports = {
  extends: ["eslint:recommended", "plugin:prettier/recommended"],
};
```

```
# package.json
{
  "devDependencies": {
    "prettier": "^2.0.0"
  }
}
```

## Relevant links
https://prettier.io/blog/2020/03/21/2.0.0.html requires Node 10+

**Comment by ArsenMelikyan** [comment]
Agreed. Currently Node 6 is used and it will hold back from updating/adding new eslint plugins.

**Comment by sinani** [comment]
you should pin exact Prettier version: https://prettier.io/docs/en/install.html

**Comment by efueger** [comment]
@SkipKayhil - apologies for dropping this!
- I'll close it for now, but let me know if we should investigate further.
