### ISSUE TITLE
eslint-8 channel?

### ISSUE THREAD

**Issue by gwvt** [codeclimate/codeclimate-eslint#574]
Will eslint 8 be supported?

**Comment by gwvt** [comment]
Thank you @fede-moya! When I configure as above I get a Code Climate build error with this output:
```
Module not supported: tailwindcss
Module not supported: plugin:tailwindcss/recommended
Module not supported: storybook
Module not supported: plugin:storybook/recommended
/usr/local/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:821
                throw new Error(message);
                      ^

Error: .eslintrc.js:
	Environment key "vue/setup-compiler-macros" is unknown

    at /usr/local/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:821:23
    at Array.forEach (<anonymous>)
    at ConfigValidator.validateEnvironment (/usr/local/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:815:34)
    at ConfigValidator.validateConfigArray (/usr/local/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:965:18)
    at CascadingConfigArrayFactory._finalizeConfigArray (/usr/local/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3886:23)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/usr/local/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3692:21)
    at CLIEngine.isPathIgnored (/usr/local/node_modules/eslint/lib/cli-engine/cli-engine.js:990:18)
    at ESLint.isPathIgnored (/usr/local/node_modules/eslint/lib/eslint/eslint.js:693:26)
    at isFileIgnoredByLibrary (/usr/src/app/lib/eslint.js:114:22)
    at /usr/src/app/lib/eslint.js:151:35

Node.js v17.3.1
```
The relevant parts of my `.eslintrc.js` file are:
```
module.exports = {
  env: {
    jest: true,
    node: true,
    'vue/setup-compiler-macros': true,
  },
  extends: [
    'eslint:recommended',
    'airbnb-base',
    'plugin:vue/vue3-recommended',
    'plugin:tailwindcss/recommended',
    'plugin:storybook/recommended',
  ],
  ...
```
Any suggestions on how to fix this?

**Comment by danielwwc** [comment]
+1 
I'm facing the same issue. Referring to the available engines, it only supported up to eslint-7.
https://github.com/codeclimate/codeclimate/blob/master/config/engines.yml#L77-L83
