### ISSUE TITLE
eslint config file path is ignored.

### ISSUE THREAD

**Issue by unageanu** [codeclimate/codeclimate-eslint#82]
Hi.
I specified a eslint config file path within my `.codeclimate.yml`, but it ignored.
My .codeclimate.yml looks like below:

```
engines:
  eslint:
    
    enabled: true

    config:
      config: sites/config/.eslintrc
```

I think it got worse when a creation of a CLIEngine ( `new CLIEngine(options)` ) moved to the top of the file by [this commit](https://github.com/codeclimate/codeclimate-eslint/commit/fbfb61a834be0f70c890338d26354e87f47deb4d). It seems that the creation must be after [the processing of options]( https://github.com/codeclimate/codeclimate-eslint/blob/master/bin/eslint.js#L163).
What do you think about it?

**Comment by pbrisbin** [comment]
Hi @unageanu ,

I think the issue is the doubly-nested `config` in your yaml. Can you try:

```yaml
engines:
  eslint:
    enabled: true
    config: sites/config/.eslintrc
```

?

Also, if you run `CODECLIMATE_DEBUG=1 codeclimate analyze` you should find a debug-level log entry showing the exact contents of the `/config.json` being passed to the engine.

**Comment by unageanu** [comment]
@pbrisbin, Thanks for reply.
I tried your adviced setting,

```yaml
engines:
  eslint:
    enabled: true
    config: sites/config/.eslintrc
```

But error occurred.

```shell
$ CODECLIMATE_DEBUG=1 /usr/local/bin/codeclimate analyze                                                                                     
Starting analysis
Running eslint: |[DEBUG] engine config: "{\"enabled\":true,\"config\":\"sites/config/.eslintrc\",\"include_paths\":[\".gitignore\",\"Procfile\",\"config.ru\",\"config/\",\"sites/.gitignore\",\"sites/gulpfile.js\",\"sites/package.json\",\"sites/src/\",\"sites/tasks/\",\"sites/cache/\",\"src/\",\"log/\",\"build/\",\"app.json\",\"circle.yml\",\"sample_agents/\",\"Gemfile\",\".codeclimate.yml\",\"README.md\",\"Gemfile.lock\",\"log.txt\"]}"
[DEBUG] docker run: ["docker", "run", "--name", "cc-engines-eslint-19f2fa83-6ebf-4210-bb21-9623bc590214", "--cap-drop", "all", "--label", "com.codeclimate.label=fbec8dfe-c8e5-4010-8f17-aabb318c13ee", "--memory", "512000000", "--memory-swap", "-1", "--net", "none", "--rm", "--volume", "/home/aaa/share/src/jiji/jiji2:/code:ro", "--volume", "/tmp/cc/ac30af3a-a1a4-4ecc-a3ca-935bae9ad572:/config.json:ro", "--user", "9000:9000", "codeclimate/codeclimate-eslint"]
Running eslint: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine eslint failed with status 1 and stderr 
No rules are configured. Make sure you have added a config file with rules enabled.
See our documentation at https://docs.codeclimate.com/docs/eslint for more information.
[DEBUG] backtrace: /usr/src/app/lib/cc/analyzer/raising_container_listener.rb:23:in `finished'
        /usr/src/app/lib/cc/analyzer/composite_container_listener.rb:17:in `block in finished'
        /usr/src/app/lib/cc/analyzer/composite_container_listener.rb:17:in `each'
        /usr/src/app/lib/cc/analyzer/composite_container_listener.rb:17:in `finished'
        /usr/src/app/lib/cc/analyzer/container.rb:74:in `run'
        /usr/src/app/lib/cc/analyzer/engine.rb:47:in `run'
        /usr/src/app/lib/cc/analyzer/engines_runner.rb:60:in `block in run_engine'
        /usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:74:in `with_spinner'
        /usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:55:in `block in engine_running'
        /usr/src/app/lib/cc/analyzer/formatters/formatter.rb:18:in `engine_running'
        /usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:54:in `engine_running'
        /usr/src/app/lib/cc/analyzer/engines_runner.rb:59:in `run_engine'
        /usr/src/app/lib/cc/analyzer/engines_runner.rb:23:in `block in run'
        /usr/src/app/lib/cc/analyzer/engines_runner.rb:23:in `each'
        /usr/src/app/lib/cc/analyzer/engines_runner.rb:23:in `run'
        /usr/src/app/lib/cc/cli/analyze.rb:20:in `block in run'
        /usr/src/app/lib/cc/cli/analyze.rb:18:in `chdir'
        /usr/src/app/lib/cc/cli/analyze.rb:18:in `run'
        /usr/src/app/lib/cc/cli/command.rb:24:in `execute'
        /usr/src/app/lib/cc/cli/runner.rb:25:in `run'
        /usr/src/app/lib/cc/cli/runner.rb:9:in `run'
        /usr/src/app/bin/codeclimate:9:in `<main>'
```

I think the setting key are correct [as of the document](https://docs.codeclimate.com/docs/eslint#section-adding-a-eslintrc-js).

I also tried to run `CODECLIMATE_DEBUG=1 codeclimate analyze` using the original settings. 

```shell
$ CODECLIMATE_DEBUG=1 /usr/local/bin/codeclimate analyze
[DEBUG] engine config: "{\"enabled\":true,\"config\":{\"config\":\"sites/config/.eslintrc\"},\"include_paths\":[\".gitignore\",\"Procfile\",\"config.ru\",\"config/\",\"sites/.gitignore\",\"sites/gulpfile.js\",\"sites/package.json\",\"sites/src/\",\"sites/tasks/\",\"sites/cache/\",\"src/\",\"log/\",\"build/\",\"app.json\",\"circle.yml\",\"sample_agents/\",\"Gemfile\",\".codeclimate.yml\",\"README.md\",\"Gemfile.lock\",\"log.txt\"]}"
[DEBUG] docker run: ["docker", "run", "--name", "cc-engines-eslint-385be30a-0e6b-433b-a705-ee5c954a2133", "--cap-drop", "all", "--label", "com.codeclimate.label=f8a98f3c-811c-4335-af7a-ab8c50dc1868", "--memory", "512000000", "--memory-swap", "-1", "--net", "none", "--rm", "--volume", "/home/aaa/share/src/jiji/jiji2:/code:ro", "--volume", "/tmp/cc/176c7d9e-9ee0-4f74-9a7c-8e1ace8e3354:/config.json:ro", "--user", "9000:9000", "codeclimate/codeclimate-eslint"]
[DEBUG] engine output: "{\"type\":\"issue\",\"categories\":[\"Style\"],\"check_name\":\"fatal\",\"description\":\"Parsing error: Illegal import declaration\",\"content\":{\"body\":\"For more information visit Source: http://eslint.org/docs/rules/\\n\"},\"location\":{\"path\":\"sites/src/js/composing/modules.js\",\"positions\":{\"begin\":{\"line\":1,\"column\":2},\"end\":{\"line\":1,\"column\":2}}},\"remediation_points\":50000}"
...
```
the `config` entry is exists in the `engine config` log, However, it's ignored.

**Comment by pbrisbin** [comment]
Can you post the content of `sites/config/.eslintrc`?

Even better, if it's possible for me to get a copy of your project (you can email me a tar archive if it's not OSS: pat at codeclimate dot com), I could reproduce locally and definitely get to the bottom of it.

**Comment by unageanu** [comment]
@pbrisbin
My project is bellow:
https://github.com/unageanu/jiji2/tree/develop

I am testing `.codeclimate.yml` on `develop` branch.

```shell
$ git clone -b develop https://github.com/unageanu/jiji2.git
$ cd jiji2
$ /usr/local/bin/codeclimate analyze
```

Because `.eslintrc` has been ignored, It prints warnings like this.

```
== sites/src/js/viewmodel/widgets/table-model.js (1 issue) ==
1: Parsing error: Illegal import declaration [eslint]
```

**Comment by pbrisbin** [comment]
Hello again @unageanu. So sorry for needing to catch up on this, but your guess about the problem being `cli` being instantiated before `options` are fully set up was totally right. I've tested a fix locally on your repo and will now work on getting it deployed. Thanks!

**Comment by unageanu** [comment]
Thanks! @pbrisbin :+1:
