### ISSUE TITLE
[eslint-2] Cannot find module estraverse-fb

### ISSUE THREAD

**Issue by pbrisbin** [codeclimate/codeclimate-eslint#91]
```
Error: Cannot find module 'estraverse-fb'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at monkeypatch (/usr/src/app/node_modules/babel-eslint/index.js:59:32)
    at Object.exports.parse (/usr/src/app/node_modules/babel-eslint/index.js:422:5)
    at parse (/usr/src/app/node_modules/eslint/lib/eslint.js:577:27)
    at EventEmitter.module.exports.api.verify (/usr/src/app/node_modules/eslint/lib/eslint.js:715:19)
    at processText (/usr/src/app/node_modules/eslint/lib/cli-engine.js:187:27)
    at processFile (/usr/src/app/node_modules/eslint/lib/cli-engine.js:227:18)
    at executeOnFile (/usr/src/app/node_modules/eslint/lib/cli-engine.js:603:23)
```

**Comment by dblandin** [comment]
Seems to be fixed in the `eslint-2` channel following the `babel-eslint` version bump.

Going to go ahead and close this issue.
